### PR TITLE
Allow Custom Emojis to be used with a callback

### PR DESCRIPTION
**Pull request by KyleBoyer**

### CODE REVIEW

**Comment by KyleBoyer** [comment]
@gazmull Mind merging/looking at this when you get a chance?

**Comment by gazmull** [comment]
Thanks for another PR. Before I review the changes within the source code, can you provide me at least an example where this is convenient to use?

**Comment by KyleBoyer** [comment]
Yea! I’m not sure if you’re familiar with different Pokémon bots for discord, but this allows me to use a paginated list of Pokémon spawns, and add a custom emoji under it, to simulate throwing a pokeball, as opposed to typing out a message back to the bot.

**Comment by KyleBoyer** [comment]
Another example could be a refresh button, so when you add a custom emoji, you can use the callback to make a DB/API call and update the embeds.

**Comment by KyleBoyer** [comment]
Also I will be submitting another PR soon to allow multiple authorized users(eg trading).

**Pull request closed without merging**
