### PR TITLE
Allow for disabling of the delete button for public menus

### PR DESCRIPTION
**Pull request by KyleBoyer**

### CODE REVIEW

**Comment by KyleBoyer** [comment]
@gazmull How does this look?

**Comment by gazmull** [comment]
Before merging, I'm thinking of tweaking or adding more to it. 👍

**Comment by gazmull** [comment]
LGTM. How about some tests with yours or any suggestions for any changes before merging?

**Comment by KyleBoyer** [comment]
@gazmull what’s up with line 500?

**Comment by gazmull** [comment]
Since `ALL` type overrides any further call of `setDisabledNavigationEmojis()`, I just made fun of it. 😆 

Regardless, normally navigation emojis shouldn't be affected, but in case my ignorance came upon me, feel free to make changes.

**Pull request merged**
